# 워크플로우 이름
name: hello-githubAction

# 워크플로우가 트리거 될 이벤트들 명시
on:
# push나 pull request가 일어나면 동작하도록 구현
 [push, pull_request]

# 워크플로우에서 실행할 job
jobs:
  # job의 이름
  testJob:
    # job이 돌아갈 환경
    runs-on: ubuntu-latest

    # job에서 동작할 task들의 모음
    steps:
      # 오픈소스 커뮤니티의 액션을 사용할 것을 명시
      # 이 액션은 로컬 리포지토리의 환경을 러너로 복사하는 액션
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            sync ./dist s3://cdn-t
