# main.yml
name: master

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    # main 브랜치에서 push, pull_request 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master


      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            sync ./dist s3://cdn-t
